// Fixtures
export const containerRect = Object.freeze({
  x: 50,
  y: 50,
  top: 20,
  left: 20,
  width: 300,
  height: 300,
  bottom: 300,
  right: 300,
}) as DOMRect;

export const movableRect = Object.freeze({
  x: 30,
  y: 30,
  top: 30,
  left: 30,
  width: 50,
  height: 50,
  bottom: 50,
  right: 50,
}) as DOMRect;

export const unbounded = Object.freeze({
  origin: {
    x: 55,
    y: 55,
  },
  moves: [
    { x: 150, y: -999 },
    { x: 999, y: 150 },
    { x: 150, y: 999 },
    { x: -999, y: 150 },
    { x: -999, y: -999 },
    { x: 999, y: 999 },
    { x: -999, y: 999 },
    { x: 999, y: -999 },
  ],
  results: [
    {
      origin: { x: 55, y: 55 },
      position: { x: 150, y: -999 },
      delta: { x: 95, y: -1054 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: 999, y: 150 },
      delta: { x: 944, y: 95 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: 150, y: 999 },
      delta: { x: 95, y: 944 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: -999, y: 150 },
      delta: { x: -1054, y: 95 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: -999, y: -999 },
      delta: { x: -1054, y: -1054 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: 999, y: 999 },
      delta: { x: 944, y: 944 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: -999, y: 999 },
      delta: { x: -1054, y: 944 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: 999, y: -999 },
      delta: { x: 944, y: -1054 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
  ],
});

export const bounded = Object.freeze({
  origin: {
    x: 55,
    y: 55,
  },
  moves: [
    { x: 150, y: -999 },
    { x: 999, y: 150 },
    { x: 150, y: 999 },
    { x: -999, y: 150 },
    { x: -999, y: -999 },
    { x: 999, y: 999 },
    { x: -999, y: 999 },
    { x: 999, y: -999 },
  ],
  results: [
    {
      origin: { x: 55, y: 55 },
      position: { x: 150, y: -999 },
      delta: { x: 95, y: -10 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: 999, y: 150 },
      delta: { x: 240, y: 95 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: 150, y: 999 },
      delta: { x: 95, y: 240 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: -999, y: 150 },
      delta: { x: -10, y: 95 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: -999, y: -999 },
      delta: { x: -10, y: -10 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: 999, y: 999 },
      delta: { x: 240, y: 240 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: -999, y: 999 },
      delta: { x: -10, y: 240 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
    {
      origin: { x: 55, y: 55 },
      position: { x: 999, y: -999 },
      delta: { x: 240, y: -10 },
      originRect: {
        x: 30,
        y: 30,
        top: 30,
        left: 30,
        width: 50,
        height: 50,
        bottom: 50,
        right: 50,
      },
      moving: true,
      startedMoving: false,
      stoppedMoving: false,
    },
  ],
});
